//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recipe_App.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        internal static string AddRecipeEnglish {
            get {
                return ResourceManager.GetString("AddRecipeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarif Ekle.
        /// </summary>
        internal static string AddRecipeTurkish {
            get {
                return ResourceManager.GetString("AddRecipeTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesTabEn {
            get {
                return ResourceManager.GetString("CategoriesTabEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string CategoriesTabTR {
            get {
                return ResourceManager.GetString("CategoriesTabTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string CategoryBreakfastEnglish {
            get {
                return ResourceManager.GetString("CategoryBreakfastEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kahvaltı.
        /// </summary>
        internal static string CategoryBreakfastTurkish {
            get {
                return ResourceManager.GetString("CategoryBreakfastTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string CategoryDessertsEN {
            get {
                return ResourceManager.GetString("CategoryDessertsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatlılar.
        /// </summary>
        internal static string CategoryDessertsTR {
            get {
                return ResourceManager.GetString("CategoryDessertsTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string CategoryDinnerEnglish {
            get {
                return ResourceManager.GetString("CategoryDinnerEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akşam Yemeği.
        /// </summary>
        internal static string CategoryDinnerTurkish {
            get {
                return ResourceManager.GetString("CategoryDinnerTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoryEnglish {
            get {
                return ResourceManager.GetString("CategoryEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string CategoryLunchEnglish {
            get {
                return ResourceManager.GetString("CategoryLunchEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğlen Yemeği.
        /// </summary>
        internal static string CategoryLunchTurkish {
            get {
                return ResourceManager.GetString("CategoryLunchTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Bites.
        /// </summary>
        internal static string CategoryQuickBitesEN {
            get {
                return ResourceManager.GetString("CategoryQuickBitesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperatifler.
        /// </summary>
        internal static string CategoryQuickBitesTR {
            get {
                return ResourceManager.GetString("CategoryQuickBitesTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salads.
        /// </summary>
        internal static string CategorySaladsEN {
            get {
                return ResourceManager.GetString("CategorySaladsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salatalar.
        /// </summary>
        internal static string CategorySaladsTR {
            get {
                return ResourceManager.GetString("CategorySaladsTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string CategoryTurkish {
            get {
                return ResourceManager.GetString("CategoryTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string ChooseImageButtonEnglish {
            get {
                return ResourceManager.GetString("ChooseImageButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf Seç.
        /// </summary>
        internal static string ChooseImageButtonTurkish {
            get {
                return ResourceManager.GetString("ChooseImageButtonTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonEN {
            get {
                return ResourceManager.GetString("DeleteButtonEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string DeleteButtonTR {
            get {
                return ResourceManager.GetString("DeleteButtonTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteRecipesButtonEN {
            get {
                return ResourceManager.GetString("DeleteRecipesButtonEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string DeleteRecipesButtonTR {
            get {
                return ResourceManager.GetString("DeleteRecipesButtonTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditRecipeButtonEN {
            get {
                return ResourceManager.GetString("EditRecipeButtonEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        internal static string EditRecipeButtonTR {
            get {
                return ResourceManager.GetString("EditRecipeButtonTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string IngredientsEnglish {
            get {
                return ResourceManager.GetString("IngredientsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzemeler.
        /// </summary>
        internal static string IngredientsTurkish {
            get {
                return ResourceManager.GetString("IngredientsTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        internal static string MainPageAddRecipeButtonEN {
            get {
                return ResourceManager.GetString("MainPageAddRecipeButtonEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Tarif.
        /// </summary>
        internal static string MainPageAddRecipeButtonTR {
            get {
                return ResourceManager.GetString("MainPageAddRecipeButtonTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariflerim.
        /// </summary>
        internal static string MainPageSearchRecipeButtonTR {
            get {
                return ResourceManager.GetString("MainPageSearchRecipeButtonTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MainPageSearchRecipesbuttonEN {
            get {
                return ResourceManager.GetString("MainPageSearchRecipesbuttonEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesEnglish {
            get {
                return ResourceManager.GetString("NotesEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notlar.
        /// </summary>
        internal static string NotesTurkish {
            get {
                return ResourceManager.GetString("NotesTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string QuickSearchEN {
            get {
                return ResourceManager.GetString("QuickSearchEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string QuickSearchTR {
            get {
                return ResourceManager.GetString("QuickSearchTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string RecipeEnglish {
            get {
                return ResourceManager.GetString("RecipeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Name.
        /// </summary>
        internal static string RecipeNameEnglish {
            get {
                return ResourceManager.GetString("RecipeNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarif Adı.
        /// </summary>
        internal static string RecipeNameTurkish {
            get {
                return ResourceManager.GetString("RecipeNameTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarif.
        /// </summary>
        internal static string RecipeTurkish {
            get {
                return ResourceManager.GetString("RecipeTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonEnglish {
            get {
                return ResourceManager.GetString("SaveButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string SaveButtonTurkish {
            get {
                return ResourceManager.GetString("SaveButtonTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchTabEN {
            get {
                return ResourceManager.GetString("SearchTabEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string SearchTabTR {
            get {
                return ResourceManager.GetString("SearchTabTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string TakePhotoButtonEnglish {
            get {
                return ResourceManager.GetString("TakePhotoButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf çek.
        /// </summary>
        internal static string TakePhotoButtonTurkish {
            get {
                return ResourceManager.GetString("TakePhotoButtonTurkish", resourceCulture);
            }
        }
    }
}
